server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway1
  cloud:
    gateway:
      routes:
      - id: forex-service
        uri: http://localhost:8081
        predicates:
            - Path=/currency-exchange/**
      - id: currency-conversion-service
        uri: http://localhost:8082
        predicates:
            - Path=/currency/**
